// codes/laravel-react/resources/js/pages/products/edit.tsx
import AppLayout from '@/layouts/app-layout'
import { Head, useForm } from '@inertiajs/react'
import { type BreadcrumbItem } from '@/types'

export default function ProductEdit({ product }: { product: any }) {
    const breadcrumbs: BreadcrumbItem[] = [
        { title: 'Products', href: '/products' },
        { title: 'Edit Product', href: `/products/${product.id}/edit` }
      ]
      
  const { data, setData, put, processing, errors } = useForm({
    name: product.name,
    price: product.price,
    description: product.description || '',
  })

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    put(`/products/${product.id}`)
  }

  return (
    <AppLayout breadcrumbs={breadcrumbs}>
      <Head title="Edit Product" />
      <div className="container mx-auto p-4 max-w-xl">
        <h1 className="text-2xl font-bold mb-4">Edit Product</h1>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <input
              type="text"
              className="form-input w-full"
              placeholder="Product name"
              value={data.name}
              onChange={(e) => setData('name', e.target.value)}
            />
            {errors.name && <div className="text-red-500 text-sm">{errors.name}</div>}
          </div>

          <div>
            <input
              type="text"
              className="form-input w-full"
              placeholder="Price"
              value={data.price}
              onChange={(e) => setData('price', e.target.value)}
            />
            {errors.price && <div className="text-red-500 text-sm">{errors.price}</div>}
          </div>

          <div>
            <textarea
              className="form-textarea w-full"
              placeholder="Description"
              value={data.description}
              onChange={(e) => setData('description', e.target.value)}
            />
            {errors.description && <div className="text-red-500 text-sm">{errors.description}</div>}
          </div>

          <button
            type="submit"
            className="bg-yellow-500 text-white px-4 py-2 rounded hover:bg-yellow-600"
            disabled={processing}
          >
            Update
          </button>
        </form>
      </div>
    </AppLayout>
  )
}

// codes/product-crud-vue/resources/js/pages/products/edit.vue
<template>
    <AppLayout :breadcrumbs="breadcrumbs">
      <Head title="Edit Product" />
      <div class="container mx-auto p-4 max-w-xl">
        <h1 class="text-2xl font-bold mb-4">Edit Product</h1>
  
        <form @submit.prevent="handleSubmit" class="space-y-4">
          <div>
            <input
              type="text"
              v-model="form.name"
              class="form-input w-full"
              placeholder="Product name"
            />
            <div v-if="errors.name" class="text-red-500 text-sm">{{ errors.name }}</div>
          </div>
  
          <div>
            <input
              type="text"
              v-model="form.price"
              class="form-input w-full"
              placeholder="Price"
            />
            <div v-if="errors.price" class="text-red-500 text-sm">{{ errors.price }}</div>
          </div>
  
          <div>
            <textarea
              v-model="form.description"
              class="form-textarea w-full"
              placeholder="Description"
            ></textarea>
            <div v-if="errors.description" class="text-red-500 text-sm">{{ errors.description }}</div>
          </div>
  
          <button
            type="submit"
            class="bg-yellow-500 text-white px-4 py-2 rounded hover:bg-yellow-600"
            :disabled="processing"
          >
            Update
          </button>
        </form>
      </div>
    </AppLayout>
  </template>
  
  <script>
  import { ref } from 'vue';
  import { useForm } from '@inertiajs/vue3';
  import AppLayout from '@/layouts/AppLayout.vue';
  
  export default {
    components: { AppLayout },
    props: {
      product: Object,
    },
    setup(props) {
      const { data, setData, put, processing, errors } = useForm({
        name: props.product.name,
        price: props.product.price,
        description: props.product.description || '',
      });
  
      const breadcrumbs = ref([
        { title: 'Products', href: '/products' },
        { title: 'Edit Product', href: `/products/${props.product.id}/edit` },
      ]);
  
      const handleSubmit = () => {
        put(`/products/${props.product.id}`);
      };
  
      return { data, setData, put, processing, errors, breadcrumbs, handleSubmit };
    },
  };
  </script>
